import { BasePlant, ModPlant, AllyZombie, ModLevel } from '../types';

// ============================================
// BASE PLANTS (Plantas Originales de PvZ 1)
// ============================================
export const basePlants: BasePlant[] = [
  { id: 'peashooter', name: 'Guisante', nameEn: 'Peashooter', description: 'Dispara guisantes a los zombis. Básica pero efectiva.', sunCost: 100, recharge: 'fast', toughness: 300, behavior: 'Dispara guisantes individuales en línea recta', emoji: '🌱', color: '#4caf50' },
  { id: 'sunflower', name: 'Girasol', nameEn: 'Sunflower', description: 'Produce soles adicionales para plantar más.', sunCost: 50, recharge: 'fast', toughness: 300, behavior: 'Genera 25 soles cada ~24 segundos', emoji: '🌻', color: '#ffd54f' },
  { id: 'wall-nut', name: 'Nuez', nameEn: 'Wall-Nut', description: 'Barrera resistente. Bloquea zombis por mucho tiempo.', sunCost: 50, recharge: 'slow', toughness: 4000, behavior: 'Actúa como escudo estático', emoji: '🥜', color: '#8d6e63' },
  { id: 'potato-mine', name: 'Minabomba', nameEn: 'Potato Mine', description: 'Explota al contacto con zombis. Necesita armarse.', sunCost: 25, recharge: 'slow', toughness: 300, behavior: 'Se arma en ~14s, luego explota al contacto', emoji: '💣', color: '#a1887f' },
  { id: 'snow-pea', name: 'Guisante Helado', nameEn: 'Snow Pea', description: 'Dispara guisantes helados que ralentizan zombis.', sunCost: 175, recharge: 'fast', toughness: 300, behavior: 'Dispara + ralentiza', emoji: '❄️', color: '#81d4fa' },
  { id: 'chomper', name: 'Boca Chica', nameEn: 'Chomper', description: 'Devora zombis enteros. Vulnerable mientras digiere.', sunCost: 150, recharge: 'fast', toughness: 300, behavior: 'Devora zombis de un bocado (cooldown largo)', emoji: '🪴', color: '#7b1fa2' },
  { id: 'repeater', name: 'Repetidora', nameEn: 'Repeater', description: 'Dispara dos guisantes seguidos.', sunCost: 200, recharge: 'fast', toughness: 300, behavior: 'Disparo doble', emoji: '🌿', color: '#388e3c' },
  { id: 'puff-shroom', name: 'Champiñón Puf', nameEn: 'Puff-shroom', description: 'Dispara esporas cortas. Gratis. Nocturno.', sunCost: 0, recharge: 'fast', toughness: 300, behavior: 'Alcance corto. Desaparece al final del nivel (nocturno)', emoji: '🍄', color: '#ce93d8' },
  { id: 'sun-shroom', name: 'Champiñón Solar', nameEn: 'Sun-shroom', description: 'Produce soles. Crece con el tiempo.', sunCost: 25, recharge: 'fast', toughness: 300, behavior: 'Genera soles, crece de pequeño a grande', emoji: '🍄', color: '#fff176' },
  { id: 'fume-shroom', name: 'Champiñón Humo', nameEn: 'Fume-shroom', description: 'Dispara humo que atraviesa escudos.', sunCost: 75, recharge: 'fast', toughness: 300, behavior: 'Humo penetrante, nocturno', emoji: '💨', color: '#9575cd' },
  { id: 'grave-buster', name: 'Come Tumbas', nameEn: 'Grave Buster', description: 'Destruye tumbas en el jardín.', sunCost: 75, recharge: 'medium', toughness: 300, behavior: 'Se planta sobre tumbas y las destruye', emoji: '🪦', color: '#4e342e' },
  { id: 'hypno-shroom', name: 'Champiñón Hipnosis', nameEn: 'Hypno-shroom', description: 'Hipnotiza al zombi que lo come.', sunCost: 75, recharge: 'slow', toughness: 300, behavior: 'Gira al zombi hacia el lado enemigo', emoji: '🌀', color: '#e91e63' },
  { id: 'scaredy-shroom', name: 'Champiñón Miedica', nameEn: 'Scaredy-shroom', description: 'Dispara largo alcance. Se esconde si hay zombis cerca.', sunCost: 25, recharge: 'fast', toughness: 300, behavior: 'Se esconde al acercarse zombis', emoji: '😱', color: '#ba68c8' },
  { id: 'ice-shroom', name: 'Champiñón Hielo', nameEn: 'Ice-shroom', description: 'Congela todos los zombis en pantalla. Nocturno.', sunCost: 75, recharge: 'very-slow', toughness: 300, behavior: 'Congelación masiva', emoji: '🧊', color: '#e1f5fe' },
  { id: 'doom-shroom', name: 'Champiñón Fatal', nameEn: 'Doom-shroom', description: 'Explosión devastadora. Deja cráter. Nocturno.', sunCost: 125, recharge: 'very-slow', toughness: 300, behavior: 'Explosión masiva + cráter', emoji: '☢️', color: '#b71c1c' },
  { id: 'lily-pad', name: 'Nenúfar', nameEn: 'Lily Pad', description: 'Permite plantar sobre el agua.', sunCost: 25, recharge: 'fast', toughness: 300, behavior: 'Superficie flotante', emoji: '🪷', color: '#4caf50' },
  { id: 'squash', name: 'Calabaza Aplastadora', nameEn: 'Squash', description: 'Aplasta al zombi más cercano.', sunCost: 50, recharge: 'slow', toughness: 300, behavior: 'Salta y aplasta', emoji: '🎃', color: '#e65100' },
  { id: 'threepeater', name: 'Tripitidora', nameEn: 'Threepeater', description: 'Dispara en 3 filas simultáneamente.', sunCost: 325, recharge: 'fast', toughness: 300, behavior: 'Triple disparo horizontal', emoji: '🌿', color: '#2e7d32' },
  { id: 'tangle-kelp', name: 'Alga Enredadera', nameEn: 'Tangle Kelp', description: 'Arrastra bajo el agua al zombi más cercano.', sunCost: 25, recharge: 'slow', toughness: 300, behavior: 'Ahoga un zombi (un solo uso)', emoji: '🌊', color: '#00695c' },
  { id: 'jalapeno', name: 'Jalapeño', nameEn: 'Jalapeno', description: 'Quema toda una fila de zombis.', sunCost: 125, recharge: 'slow', toughness: 300, behavior: 'Explosión en línea recta', emoji: '🌶️', color: '#d32f2f' },
  { id: 'spikeweed', name: 'Punzante', nameEn: 'Spikeweed', description: 'Daña zombis que lo pisan. Destruye ruedas.', sunCost: 100, recharge: 'fast', toughness: 300, behavior: 'Daño continuo por contacto', emoji: '🌵', color: '#689f38' },
  { id: 'torchwood', name: 'Leño Antorcha', nameEn: 'Torchwood', description: 'Los guisantes que pasan se vuelven bolas de fuego.', sunCost: 175, recharge: 'fast', toughness: 300, behavior: 'Convierte proyectiles en fuego', emoji: '🔥', color: '#bf360c' },
  { id: 'tall-nut', name: 'Nuez Alta', nameEn: 'Tall-Nut', description: 'Barrera muy alta. No se puede saltar.', sunCost: 125, recharge: 'slow', toughness: 8000, behavior: 'Muro impenetrable por salto/volador', emoji: '🧱', color: '#6d4c41' },
  { id: 'sea-shroom', name: 'Champiñón Marino', nameEn: 'Sea-shroom', description: 'Dispara bajo el agua. Nocturno.', sunCost: 0, recharge: 'fast', toughness: 300, behavior: 'Planta acuática nocturna', emoji: '🐚', color: '#80deea' },
  { id: 'plantern', name: 'Farol', nameEn: 'Plantern', description: 'Ilumina la niebla y revela zombis.', sunCost: 25, recharge: 'fast', toughness: 300, behavior: 'Campo de visión', emoji: '🏮', color: '#ffcc80' },
  { id: 'cactus', name: 'Cactus', nameEn: 'Cactus', description: 'Dispara espinas que pinchan globos.', sunCost: 125, recharge: 'fast', toughness: 300, behavior: 'Anti-aéreo + disparo normal', emoji: '🌵', color: '#558b2f' },
  { id: 'bloomerang', name: 'Boomerang', nameEn: 'Bloomerang', description: 'Lanza un boomerang que golpea ida y vuelta.', sunCost: 100, recharge: 'fast', toughness: 300, behavior: 'Golpea zombis ida y vuelta', emoji: '🪃', color: '#a1887f' },
  { id: 'split-pea', name: 'Guisante Dividido', nameEn: 'Split Pea', description: 'Dispara hacia ambos lados.', sunCost: 125, recharge: 'fast', toughness: 300, behavior: 'Disparo frontal doble + trasero simple', emoji: '🫛', color: '#558b2f' },
  { id: 'starfruit', name: 'Frutiestrella', nameEn: 'Starfruit', description: 'Dispara estrellas en 5 direcciones.', sunCost: 125, recharge: 'fast', toughness: 300, behavior: 'Disparo en 5 direcciones', emoji: '⭐', color: '#ffd54f' },
  { id: 'pumpkin', name: 'Calabaza', nameEn: 'Pumpkin', description: 'Envuelve otra planta protegiéndola.', sunCost: 125, recharge: 'slow', toughness: 4000, behavior: 'Cáscara protectora externa', emoji: '🎃', color: '#e65100' },
  { id: 'magnet-shroom', name: 'Champiñón Imán', nameEn: 'Magnet-shroom', description: 'Roba objetos metálicos de los zombis.', sunCost: 100, recharge: 'fast', toughness: 300, behavior: 'Quita conos, cubos, pantallas', emoji: '🧲', color: '#7b1fa2' },
  { id: 'cabbage-pult', name: 'Lanzacoles', nameEn: 'Cabbage-pult', description: 'Lanza repollos por encima de obstáculos.', sunCost: 100, recharge: 'fast', toughness: 300, behavior: 'Tiro parabólico', emoji: '🥬', color: '#8bc34a' },
  { id: 'flower-pot', name: 'Maceta', nameEn: 'Flower Pot', description: 'Permite plantar en techo.', sunCost: 25, recharge: 'fast', toughness: 300, behavior: 'Base para plantas en azotea', emoji: '🪴', color: '#8d6e63' },
  { id: 'kernel-pult', name: 'Lanzamaíz', nameEn: 'Kernel-pult', description: 'Lanza maíz y mantequilla que paraliza.', sunCost: 100, recharge: 'fast', toughness: 300, behavior: 'Tiro parabólico + mantequilla stun', emoji: '🌽', color: '#fdd835' },
  { id: 'coffee-bean', name: 'Grano de Café', nameEn: 'Coffee Bean', description: 'Despierta a los champiñones dormidos de día.', sunCost: 75, recharge: 'fast', toughness: 300, behavior: 'Activa plantas nocturnas de día', emoji: '☕', color: '#4e342e' },
  { id: 'garlic', name: 'Ajo', nameEn: 'Garlic', description: 'Los zombis que lo mordisquen cambian de fila.', sunCost: 50, recharge: 'fast', toughness: 1000, behavior: 'Redirige zombis a filas adyacentes', emoji: '🧄', color: '#fff9c4' },
  { id: 'umbrella-leaf', name: 'Hoja Paraguas', nameEn: 'Umbrella Leaf', description: 'Protege plantas cercanas de proyectiles aéreos.', sunCost: 100, recharge: 'fast', toughness: 300, behavior: 'Escudo anti-catapulta/bungee', emoji: '☂️', color: '#4caf50' },
  { id: 'marigold', name: 'Caléndula', nameEn: 'Marigold', description: 'Produce monedas de plata y oro.', sunCost: 50, recharge: 'fast', toughness: 300, behavior: 'Genera monedas en Zen Garden', emoji: '🌼', color: '#ff9800' },
  { id: 'melon-pult', name: 'Lanzamelones', nameEn: 'Melon-pult', description: 'Lanza sandías con daño en área.', sunCost: 300, recharge: 'fast', toughness: 300, behavior: 'Tiro parabólico con splash', emoji: '🍉', color: '#4caf50' },
  { id: 'gatling-pea', name: 'Guisante Metralleta', nameEn: 'Gatling Pea', description: 'Mejora de Repetidora. Dispara 4 guisantes.', sunCost: 250, recharge: 'fast', toughness: 300, behavior: 'Cuádruple disparo (sobre Repetidora)', emoji: '🔫', color: '#1b5e20' },
  { id: 'twin-sunflower', name: 'Girasol Gemelo', nameEn: 'Twin Sunflower', description: 'Mejora de Girasol. Produce doble sol.', sunCost: 150, recharge: 'fast', toughness: 300, behavior: 'Genera doble sol (sobre Girasol)', emoji: '🌻', color: '#ffeb3b' },
  { id: 'gloom-shroom', name: 'Champiñón Penumbra', nameEn: 'Gloom-shroom', description: 'Mejora de Humo. Ataca en todas direcciones.', sunCost: 150, recharge: 'fast', toughness: 300, behavior: 'Humo 3x3 (sobre Fume-shroom)', emoji: '💨', color: '#4a148c' },
  { id: 'cattail', name: 'Espadaña', nameEn: 'Cattail', description: 'Mejora de Nenúfar. Dispara espinas a cualquier zombi.', sunCost: 225, recharge: 'fast', toughness: 300, behavior: 'Espadas dirigidas (sobre Lily Pad)', emoji: '🐈', color: '#1b5e20' },
  { id: 'winter-melon', name: 'Sandía Helada', nameEn: 'Winter Melon', description: 'Mejora de Melón. Ralentiza con splash helado.', sunCost: 200, recharge: 'fast', toughness: 300, behavior: 'Melón helado con splash (sobre Melon-pult)', emoji: '🧊', color: '#0277bd' },
  { id: 'gold-magnet', name: 'Imán Dorado', nameEn: 'Gold Magnet', description: 'Mejora de Imán. Roba oro de zombis.', sunCost: 50, recharge: 'fast', toughness: 300, behavior: 'Recoge monedas (sobre Magnet-shroom)', emoji: '🪙', color: '#ffd600' },
  { id: 'spikerock', name: 'Rocapúas', nameEn: 'Spikerock', description: 'Mejora de Punzante. Más resistente y dañino.', sunCost: 125, recharge: 'fast', toughness: 450, behavior: 'Punzante mejorado (sobre Spikeweed)', emoji: '⚡', color: '#33691e' },
  { id: 'cob-cannon', name: 'Cañón de Mazorca', nameEn: 'Cob Cannon', description: 'Mejora de Maíz. Lanzacohetes manual.', sunCost: 500, recharge: 'very-slow', toughness: 300, behavior: 'Explosión manual dirigida (sobre 2 Kernel-pult)', emoji: '🚀', color: '#f57f17' },
];

// ============================================
// MOD PLANTS (Plantas del Mod - Bowling Nuts)
// ============================================
export const modPlants: ModPlant[] = [
  {
    id: 'rolling-nut',
    name: 'Nuez Rodadora',
    description: 'Se coloca y rueda por la fila empujando y golpeando a los zombis en su camino. Funciona como planta móvil defensiva y ofensiva. Inspirada en la mecánica de Wall-Nut Bowling.',
    sunCost: 75,
    recharge: 'medium',
    toughness: 1500,
    damage: 30,
    speed: 1.5,
    behavior: 'roll',
    specialAbility: 'Rueda por la fila empujando zombis hacia atrás 1 casilla y causando 30 de daño por impacto. Cada 3 zombis golpeados pierde un tercio de su vida. Desaparece tras golpear 9 zombis.',
    unlockLevel: 'mod-plant-lvl-1',
    emoji: '🥜',
    color: '#a1887f',
    placeholderNote: 'SPRITE: Crear sprite de nuez rodante 40x40px con animación de rotación. Basar en el sprite original de Wall-Nut pero con forma esférica y efecto de giro.',
    configurable: { rollSpeed: 1.5, damagePerHit: 30, maxHits: 9, knockbackCells: 1, sunCostOverride: null },
  },
  {
    id: 'rolling-nut-red',
    name: 'Nuez Rodadora Roja Explosiva',
    description: 'Versión mejorada de la Nuez Rodadora. Rueda por la fila y explota al impactar con el primer zombi o al llegar al final del recorrido. Su explosión afecta a todos los zombis cercanos en un radio de 1.5 casillas.',
    sunCost: 150,
    recharge: 'slow',
    toughness: 2000,
    damage: 80,
    speed: 1.8,
    behavior: 'explode',
    specialAbility: 'Rueda hasta impactar un zombi o llegar al final. Explota causando 80 de daño a todos los zombis en radio 1.5 casillas. Deja un pequeño cráter que desaparece en 5 segundos.',
    unlockLevel: 'mod-plant-lvl-3',
    emoji: '💥',
    color: '#e53935',
    placeholderNote: 'SPRITE: Crear sprite de nuez roja rodante 44x44px con brillo/fulgor rojo. Animación de explosión: 6 frames. Efecto de onda expansiva.',
    configurable: { rollSpeed: 1.8, explosionDamage: 80, explosionRadius: 1.5, fuseTime: null, sunCostOverride: null },
  },
  {
    id: 'rolling-nut-giant',
    name: 'Nuez Rodadora Gigante',
    description: 'La versión más grande y potente. Ocupa visualmente más espacio, empuja zombis con más fuerza y causa más daño. Es la versión "premium" de alta inversión en soles.',
    sunCost: 250,
    recharge: 'very-slow',
    toughness: 5000,
    damage: 50,
    speed: 1.0,
    behavior: 'roll',
    specialAbility: 'Rueda más lento pero con más potencia. Empuja zombis 2 casillas hacia atrás y causa 50 de daño. Soporta hasta 20 impactos antes de destruirse. Aplasta zombis pequeños (Imp) al instante.',
    unlockLevel: 'mod-plant-lvl-5',
    emoji: '🟤',
    color: '#5d4037',
    placeholderNote: 'SPRITE: Crear sprite grande de nuez 60x60px con textura de roca. Animación pesada de giro. Efecto de sacudida al impactar.',
    configurable: { rollSpeed: 1.0, damagePerHit: 50, maxHits: 20, knockbackCells: 2, crushSmallZombies: true, sunCostOverride: null },
  },
];

// ============================================
// ALLY ZOMBIES (Zombis Aliados)
// ============================================
export const allyZombies: AllyZombie[] = [
  {
    id: 'ally-conehead',
    name: 'Zombi Cono Aliado',
    nameEn: 'Ally Conehead',
    description: 'Un zombi Conehead que ha sido reclutado. Su cono le da resistencia extra. Camina hacia la derecha y golpea zombis enemigos.',
    sunCost: 75,
    recharge: 'fast',
    hp: 650,
    damage: 20,
    attackSpeed: 0.5,
    movementSpeed: 0.35,
    specialAbility: 'El cono absorbe los primeros 370 puntos de daño. Sin cono, velocidad normal.',
    unlockLevel: 'ally-lvl-1',
    emoji: '🧟',
    color: '#7cb342',
    placeholderNote: 'SPRITE: Reutilizar sprite de Conehead original pero con una cinta verde en la cabeza (indicador aliado). Animación de caminata hacia la derecha.',
    configurable: { coneHP: 370, baseHP: 280, damagePerBite: 20, speed: 0.35 },
  },
  {
    id: 'ally-buckethead',
    name: 'Zombi Cubo Aliado',
    nameEn: 'Ally Buckethead',
    description: 'El zombi más resistente del equipo inicial. Su cubo de metal lo protege enormemente antes de recibir daño real.',
    sunCost: 125,
    recharge: 'medium',
    hp: 1350,
    damage: 20,
    attackSpeed: 0.5,
    movementSpeed: 0.35,
    specialAbility: 'El cubo absorbe 1100 puntos de daño. Al perder el cubo queda muy vulnerable.',
    unlockLevel: 'ally-lvl-2',
    emoji: '🪣',
    color: '#78909c',
    placeholderNote: 'SPRITE: Reutilizar sprite de Buckethead con cinta verde. Animación idéntica al original.',
    configurable: { bucketHP: 1100, baseHP: 250, damagePerBite: 20, speed: 0.35 },
  },
  {
    id: 'ally-pole-vaulter',
    name: 'Zombi Pértiga Aliado',
    nameEn: 'Ally Pole Vaulter',
    description: 'Usa su pértiga para saltar por encima del primer zombi enemigo que encuentra y aterrizar detrás de él.',
    sunCost: 150,
    recharge: 'medium',
    hp: 450,
    damage: 30,
    attackSpeed: 0.6,
    movementSpeed: 0.65,
    specialAbility: 'Salta sobre el primer zombi enemigo y aterriza detrás. Pierde la pértiga tras el salto (pierde velocidad extra).',
    unlockLevel: 'ally-lvl-3',
    emoji: '🏃',
    color: '#ff9800',
    placeholderNote: 'SPRITE: Sprite de Pértiga con cinta verde. Dos fases de animación: con pértiga (rápido) y sin pértiga (lento).',
    configurable: { jumpRange: 1, preJumpSpeed: 0.65, postJumpSpeed: 0.25, damagePerBite: 30, hp: 450 },
  },
  {
    id: 'ally-balloon',
    name: 'Zombi Globo Aliado',
    nameEn: 'Ally Balloon Zombie',
    description: 'Flota por encima de todo. Puede cruzar directamente a la derecha ignorando obstáculos terrestres.',
    sunCost: 175,
    recharge: 'slow',
    hp: 350,
    damage: 25,
    attackSpeed: 0.4,
    movementSpeed: 0.5,
    specialAbility: 'Vuela sobre el terreno. Inmune a ataques terrestres. Si le revientan el globo, cae y camina.',
    unlockLevel: 'ally-lvl-4',
    emoji: '🎈',
    color: '#e91e63',
    placeholderNote: 'SPRITE: Globo + zombi volando. Al caer, sprite normal de zombi caminando. Animación flotante.',
    configurable: { balloonHP: 150, walkHP: 200, damagePerBite: 25, flySpeed: 0.5, walkSpeed: 0.25 },
  },
  {
    id: 'ally-football',
    name: 'Zombi Futbolista Aliado',
    nameEn: 'Ally Football Zombie',
    description: 'El zombi más rápido del equipo. Carga con equipamiento deportivo completo.',
    sunCost: 200,
    recharge: 'slow',
    hp: 1600,
    damage: 35,
    attackSpeed: 0.7,
    movementSpeed: 0.85,
    specialAbility: 'Velocidad de carga extrema. Pierde el casco al recibir 800+ daño (velocidad normal).',
    unlockLevel: 'ally-lvl-5',
    emoji: '🏈',
    color: '#d32f2f',
    placeholderNote: 'SPRITE: Zombi con casco de fútbol americano y cinta verde. Fases con/sin casco.',
    configurable: { helmetHP: 800, baseHP: 800, chargeSpeed: 0.85, walkSpeed: 0.35, damagePerBite: 35 },
  },
  {
    id: 'ally-digger',
    name: 'Zombi Minero Aliado',
    nameEn: 'Ally Digger Zombie',
    description: 'Excava bajo tierra y aparece al otro lado del campo, caminando hacia la derecha.',
    sunCost: 150,
    recharge: 'medium',
    hp: 300,
    damage: 20,
    attackSpeed: 0.5,
    movementSpeed: 0.4,
    specialAbility: 'Se entierra al colocarlo y reaparece en la columna 7. Camina hacia la derecha.',
    unlockLevel: 'ally-lvl-6',
    emoji: '⛏️',
    color: '#795548',
    placeholderNote: 'SPRITE: Zombi con pico + cinta verde. Animación de excavación. Sin casco al emerger.',
    configurable: { emergeColumn: 7, hp: 300, damagePerBite: 20, speed: 0.4 },
  },
  {
    id: 'ally-dancer',
    name: 'Zombi Bailarín Aliado',
    nameEn: 'Ally Dancing Zombie',
    description: 'Invoca bailarines de respaldo que atacan en filas adyacentes.',
    sunCost: 250,
    recharge: 'very-slow',
    hp: 600,
    damage: 20,
    attackSpeed: 0.5,
    movementSpeed: 0.45,
    specialAbility: 'Cada ~15 segundos invoca 2 bailarines en las filas de arriba y abajo.',
    unlockLevel: 'ally-lvl-7',
    emoji: '💃',
    color: '#9c27b0',
    placeholderNote: 'SPRITE: Zombi disco con cinta verde. Bailarines mini con cinta verde. Animación de baile.',
    configurable: { summonInterval: 15, backupDancerHP: 150, damagePerBite: 20, speed: 0.45 },
  },
  {
    id: 'ally-gargantuar',
    name: 'Zombi Gargantúa Aliado',
    nameEn: 'Ally Gargantuar',
    description: 'El zombi más poderoso. Aplasta zombis enemigos de un golpe. Lento pero devastador.',
    sunCost: 500,
    recharge: 'very-slow',
    hp: 3000,
    damage: 100,
    attackSpeed: 0.2,
    movementSpeed: 0.2,
    specialAbility: 'Aplasta zombis al instante con su poste. A mitad de vida lanza un Imp aliado.',
    unlockLevel: 'final-level',
    emoji: '🗿',
    color: '#3e2723',
    placeholderNote: 'SPRITE: Gargantuar con cinta verde. Poste telegráfico. Imp mini con cinta verde. Muy lento pero enorme.',
    configurable: { hp: 3000, damagePerSmash: 100, throwImpAtHP: 1500, speed: 0.2, impHP: 200, impDamage: 30 },
  },
];

// ============================================
// MOD LEVELS (Niveles del Mod)
// ============================================
export const modLevels: ModLevel[] = [
  {
    id: 'mod-plant-lvl-1',
    name: 'Prueba de Rodamiento',
    description: 'Introducción a la Nuez Rodadora. Usa solo Peashooters, Girasoles y la nueva Nuez Rodadora para sobrevivir 3 oleadas.',
    campaign: 'plants',
    waves: 3,
    zombies: ['basic', 'cone', 'basic', 'cone', 'basic', 'flag'],
    availablePlants: ['sunflower', 'peashooter', 'wall-nut', 'rolling-nut'],
    availableAllies: [],
    unlocks: 'rolling-nut',
    unlockType: 'plant',
    difficulty: 1,
    previewWave: 'Zombis básicos + cono',
  },
  {
    id: 'mod-plant-lvl-2',
    name: 'Bolera Infernal',
    description: 'Práctica guiada con la Nuez Rodadora. El nivel está diseñado para que uses estratégicamente las nueces rodadoras en las 5 filas.',
    campaign: 'plants',
    waves: 4,
    zombies: ['basic', 'cone', 'bucket', 'basic', 'cone', 'flag'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'rolling-nut', 'wall-nut', 'snow-pea'],
    availableAllies: [],
    unlocks: 'rolling-nut-practice',
    unlockType: 'plant',
    difficulty: 2,
    previewWave: 'Zombis con cubo aparecen',
  },
  {
    id: 'mod-plant-lvl-3',
    name: 'Explosión Controlada',
    description: '¡Se desbloquea la Nuez Rodadora Roja Explosiva! Usa su poder de explosión para limpiar grupos de zombis.',
    campaign: 'plants',
    waves: 5,
    zombies: ['cone', 'basic', 'cone', 'bucket', 'basic', 'cone', 'flag'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'rolling-nut', 'rolling-nut-red', 'wall-nut', 'jalapeno'],
    availableAllies: [],
    unlocks: 'rolling-nut-red',
    unlockType: 'plant',
    difficulty: 2,
    previewWave: 'Oleadas con zombis en grupo',
  },
  {
    id: 'mod-plant-lvl-4',
    name: 'Oleada Explosiva',
    description: 'Pon a prueba la Nuez Roja en oleadas más duras. Los zombis vienen en grupos densos. La explosión es clave.',
    campaign: 'plants',
    waves: 6,
    zombies: ['cone', 'bucket', 'cone', 'bucket', 'cone', 'bucket', 'flag', 'basic'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'rolling-nut', 'rolling-nut-red', 'wall-nut', 'torchwood', 'snow-pea'],
    availableAllies: [],
    unlocks: 'rolling-nut-red-practice',
    unlockType: 'plant',
    difficulty: 3,
    previewWave: 'Cubos y conos masivos',
  },
  {
    id: 'mod-plant-lvl-5',
    name: 'El Coloso de la Bolera',
    description: 'Se desbloquea la Nuez Rodadora Gigante. Su poder es inmenso pero su coste también. Úsala sabiamente.',
    campaign: 'plants',
    waves: 7,
    zombies: ['bucket', 'cone', 'bucket', 'cone', 'bucket', 'flag', 'bucket', 'cone'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'rolling-nut', 'rolling-nut-red', 'rolling-nut-giant', 'wall-nut', 'tall-nut', 'melon-pult'],
    availableAllies: [],
    unlocks: 'rolling-nut-giant',
    unlockType: 'plant',
    difficulty: 3,
    previewWave: 'Gargantúas aparecen',
  },
  {
    id: 'ally-lvl-1',
    name: 'El Recluta Cono',
    description: '¡Primer nivel de Zombis Aliados! Desbloquea al Zombi Conehead como aliado. Combínalo con tus plantas.',
    campaign: 'allies',
    waves: 4,
    zombies: ['basic', 'basic', 'cone', 'basic', 'cone', 'flag'],
    availablePlants: ['sunflower', 'peashooter', 'wall-nut', 'rolling-nut'],
    availableAllies: ['ally-conehead'],
    unlocks: 'ally-conehead',
    unlockType: 'zombie',
    difficulty: 2,
    previewWave: 'Prueba al Conehead aliado',
  },
  {
    id: 'ally-lvl-2',
    name: 'Escudo de Cubo',
    description: 'Desbloquea al Zombi Cubo aliado. Es el tanque que tu equipo necesita.',
    campaign: 'allies',
    waves: 5,
    zombies: ['cone', 'basic', 'bucket', 'cone', 'bucket', 'flag'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'wall-nut', 'rolling-nut', 'rolling-nut-red'],
    availableAllies: ['ally-conehead', 'ally-buckethead'],
    unlocks: 'ally-buckethead',
    unlockType: 'zombie',
    difficulty: 3,
    previewWave: 'Cubos enemigos aparecen',
  },
  {
    id: 'ally-lvl-3',
    name: 'Salto Acrobático',
    description: 'Desbloquea al Zombi Pértiga aliado. Su salto sobre zombis enemigos es devastador.',
    campaign: 'allies',
    waves: 6,
    zombies: ['cone', 'bucket', 'cone', 'bucket', 'cone', 'flag', 'basic'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'snow-pea', 'rolling-nut', 'rolling-nut-red', 'wall-nut'],
    availableAllies: ['ally-conehead', 'ally-buckethead', 'ally-pole-vaulter'],
    unlocks: 'ally-pole-vaulter',
    unlockType: 'zombie',
    difficulty: 3,
    previewWave: 'Oleadas densas, usa el salto',
  },
  {
    id: 'ally-lvl-4',
    name: 'Ataque Aéreo',
    description: 'Desbloquea al Zombi Globo aliado. Su vuelo le permite ignorar obstáculos.',
    campaign: 'allies',
    waves: 7,
    zombies: ['bucket', 'cone', 'bucket', 'cone', 'bucket', 'flag', 'cone', 'bucket'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'snow-pea', 'rolling-nut', 'rolling-nut-red', 'cactus', 'wall-nut'],
    availableAllies: ['ally-conehead', 'ally-buckethead', 'ally-pole-vaulter', 'ally-balloon'],
    unlocks: 'ally-balloon',
    unlockType: 'zombie',
    difficulty: 4,
    previewWave: 'Globos enemigos + globos aliados',
  },
  {
    id: 'final-level',
    name: 'La Batalla Final',
    description: '¡DESAFÍO FINAL! Todas las mecánicas mezcladas. Usa plantas mod y zombis aliados juntos. Desbloquea al Gargantúa aliado si sobrevives.',
    campaign: 'final',
    waves: 10,
    zombies: ['bucket', 'cone', 'bucket', 'flag', 'bucket', 'cone', 'bucket', 'flag', 'bucket', 'cone', 'bucket', 'flag', 'bucket', 'cone'],
    availablePlants: ['sunflower', 'peashooter', 'repeater', 'snow-pea', 'rolling-nut', 'rolling-nut-red', 'rolling-nut-giant', 'wall-nut', 'tall-nut', 'jalapeno', 'torchwood', 'melon-pult', 'gatling-pea'],
    availableAllies: ['ally-conehead', 'ally-buckethead', 'ally-pole-vaulter', 'ally-balloon', 'ally-football', 'ally-digger', 'ally-dancer', 'ally-gargantuar'],
    unlocks: 'ally-gargantuar',
    unlockType: 'zombie',
    difficulty: 5,
    previewWave: 'TODO. ABSOLUTAMENTE TODO.',
  },
];

// ============================================
// MOD CONFIGURATION JSON (exportable)
// ============================================
export const modConfigJson = {
  mod_name: "PvZ Bowling Nuts & Ally Zombies",
  version: "1.0.0",
  target_game: "Plants vs. Zombies 1 (Original PC)",
  target_version: "1.2.0.1073 (Game of the Year Edition)",
  author: "Mod Community",
  description: "Mod que añade plantas de bolera rodante y zombis aliados jugables",
  dependencies: [],
  settings: {
    save_file: "mod_progress.json",
    log_file: "mod_debug.log",
    debug_mode: false,
    language: "es",
    max_rolling_nuts_on_screen: 3,
    ally_zombie_limit_per_level: 4,
    sun_start_amount: 50,
    lawn_mower_enabled: true,
  },
  balance: {
    rolling_nut: { base_cost: 75, cooldown_frames: 300, lifetime_hits: 9 },
    rolling_nut_red: { base_cost: 150, cooldown_frames: 600, explosion_radius_cells: 1.5 },
    rolling_nut_giant: { base_cost: 250, cooldown_frames: 900, lifetime_hits: 20 },
  },
  placeholder_assets: {
    note: "Todos los sprites son PLACEHOLDERS. Reemplazar con archivos legales del juego original o arte propio.",
    required: [
      "plants/rolling_nut.png (40x40, animated rotation)",
      "plants/rolling_nut_red.png (44x44, glow effect)",
      "plants/rolling_nut_giant.png (60x60, rock texture)",
      "zombies/ally_conehead.png (with green ribbon indicator)",
      "zombies/ally_buckethead.png (with green ribbon indicator)",
      "zombies/ally_pole_vaulter.png (two phases)",
      "zombies/ally_balloon.png (flying + falling)",
      "zombies/ally_football.png (with/without helmet)",
      "zombies/ally_digger.png (digging animation)",
      "zombies/ally_dancer.png (disco + backups)",
      "zombies/ally_gargantuar.png (with green ribbon + imp)",
      "icons/rolling_nut_icon.png (26x26)",
      "icons/rolling_nut_red_icon.png (26x26)",
      "icons/rolling_nut_giant_icon.png (26x26)",
      "sounds/rolling_impact.wav",
      "sounds/rolling_explosion.wav",
      "sounds/rolling_giant_impact.wav",
    ],
  },
};
